# Delete the Endpoint Configuration
simple_rest_adapter_config_delete:
    path: /delete
    defaults: { _controller: CIHub\Bundle\SimpleRESTAdapterBundle\Controller\ConfigController::deleteAction }
    methods:
        - GET

# Get Data of Endpoint Configuration
simple_rest_adapter_config_get:
    path: /get
    defaults: { _controller: CIHub\Bundle\SimpleRESTAdapterBundle\Controller\ConfigController::getAction }
    methods:
        - GET

# Get List of all Labels
simple_rest_adapter_config_label_list:
    path: /label-list
    defaults: { _controller: CIHub\Bundle\SimpleRESTAdapterBundle\Controller\ConfigController::labelListAction }
    methods:
        - GET

# Save the Endpoint Configuration
simple_rest_adapter_config_save:
    path: /save
    defaults: { _controller: CIHub\Bundle\SimpleRESTAdapterBundle\Controller\ConfigController::saveAction }
    methods:
        - POST

# Get List of Thumbnails
simple_rest_adapter_config_thumbnails:
    path: /thumbnails
    defaults: { _controller: CIHub\Bundle\SimpleRESTAdapterBundle\Controller\ConfigController::thumbnailsAction }
    methods:
        - GET
