# Swagger UI
simple_rest_adapter_swagger_ui:
    path: /swagger
    defaults: { _controller: CIHub\Bundle\SimpleRESTAdapterBundle\Controller\SwaggerController::userInterfaceAction }
    methods:
        - GET

# Swagger Config
simple_rest_adapter_swagger_config:
    path: /swagger-config
    defaults: { _controller: CIHub\Bundle\SimpleRESTAdapterBundle\Controller\SwaggerController::configAction }
    methods:
        - GET
